# RawNet3 reproduce recipe configuration.
# The current training:

# 4 A100 40G GPUs, `batch_size`=1024, `lr=2e-3 ~ 2e-4`
# ~4.5 days, 61 epochs
# Original model size

# Total Number of model parameters: 108.03 M
# Number of trainable parameters: 108.03 M (100.0%)
# Size: 432.12 MB

# Frontend
frontend: asteroid_frontend
frontend_conf:
    sinc_stride: 16
    sinc_kernel_size: 251
    sinc_filters: 256
    preemph_coef: 0.97
    log_term: 0.000001

# Encoder
encoder: rawnet3
encoder_conf:
  model_scale: 8
  ndim: 1024
  output_size: 1536

# Pooling
pooling: chn_attn_stat

# Projector
projector: rawnet3
projector_conf:
  output_size: 192

# Preprocessor
preprocessor: spk
preprocessor_conf:
  target_duration: 3.0  # seconds
  sample_rate: 16000
  num_eval: 3
  noise_apply_prob: 0.5
  noise_info:
  - [1.0, 'dump/raw/musan_speech.scp', [4, 7], [13, 20]]
  - [1.0, 'dump/raw/musan_noise.scp', [1, 1], [0, 15]]
  - [1.0, 'dump/raw/musan_music.scp', [1, 1], [5, 15]]
  rir_apply_prob: 0.5
  rir_scp: dump/raw/rirs.scp

# Model config
model_conf:
  extract_feats_in_collect_stats: false

# Loss
loss: aamsoftmax_sc_topk
loss_conf:
  margin: 0.3
  scale: 30
  K: 3
  mp: 0.06
  k_top: 5

# Training related
max_epoch: 200
num_att_plot: 0
num_workers: 15
cudnn_deterministic: False
cudnn_benchmark: True
drop_last_iter: True
iterator_type: category
valid_iterator_type: sequence
shuffle_within_batch: False
log_interval: 100
batch_size: 1024
valid_batch_size: 40
use_amp: True
keep_nbest_models: 3
grad_clip: 9999
best_model_criterion:
- - valid
  - eer
  - min

# Optimizer
optim: adamw  # adam_W
optim_conf:
  # betas=(0.9, 0.999) too aggressive, change to betas=(0.9, 0.95)
  # betas:
  # - 0.9
  # - 0.95
  lr: 0.002
  weight_decay: 0.00005
  amsgrad: False

# Scheduler
# just one circle of cosine annealing, no restarts
# one epoch: 3832 steps in metamidi
scheduler: CosineAnnealingWarmupRestarts
scheduler_conf:
  # first_cycle_steps: 71280 # equal to 10 epochs in voxceleb
  # first_cycle_steps: 766400 # equal to 200 epochs in metamidi
  first_cycle_steps: 366000 # equal to 60 epochs in 12m
  cycle_mult: 1.0
  max_lr: 0.002
  min_lr: 0.0002  # 0.0001
  warmup_steps: 1000
  gamma: 0.75  # does not effect if just one circle

# wandb
use_wandb: true
wandb_project: rawnet3_12m
wandb_name: train_4gpu_bs1024_60epoch
